### ISSUE TITLE
Add HEAD^ to git reset --hard in Exercise4-MergingAndReReRe

### ISSUE THREAD

**Issue by ricguti** [nnja/advanced-git#10]
Hi 👋 

Thanks for the course! I'm following it and I really like it.

I thought it could be good to add `HEAD^` to instruction 2 of Exercise4-MergingAndReReRe so it reads: `2. Use git reset --hard HEAD^ to reset...` . This because `git reset` is explained at a further point of the course, so maybe not everybody is familiarized with `git reset` when solving exercise 4.

I know that `git reset --hard HEAD^` is part of solving the exercise but maybe adding this could help the people, that aren't familiarize with `git reset`, to focus on practicing merging and rerere without peeking into the solution.

**Comment by nnja** [comment]
I think that's a great idea. If you're comfortable submitting a pull request please do so and I'd be happy to merge it.

**Comment by ricguti** [comment]
Great! I just submitted a pull request. [Add HEAD^ to git reset --hard in instructions](https://github.com/nnja/advanced-git/pull/11)

**Comment by nnja** [comment]
Closed by #11
