### ISSUE TITLE
There are no branches

### ISSUE THREAD

**Issue by joacim-boive** [nnja/advanced-git#7]
There's only master in the repo so your instructions doesn't work like in:
https://github.com/nnja/advanced-git/blob/master/exercises/Exercise4-MergingAndReReRe.md

git checkout exercise4

gives:
error: pathspec 'exercise4' did not match any file(s) known to git.

The GitHub repo only has one branch: Master
So, it makes sense. :)

**Comment by nnja** [comment]
If you look at the top of the file, under the overview in the prerequisites section, it very clearly says:

```
### Prerequisite
You should have the [`advanced-git-exercises`](https://github.com/nnja/advanced-git-exercises)  repository cloned locally. Checkout the `exercise4` branch:

$> git checkout exercise4
Switched to branch 'exercise4'
```

You need to have this repo: https://github.com/nnja/advanced-git-exercises cloned to complete the exercise.

See: https://github.com/nnja/advanced-git/blame/master/exercises/Exercise4-MergingAndReReRe.md#L7-L13

Closing, as everything works as expected and is clearly documented.
