### ISSUE TITLE
Simple typo

### ISSUE THREAD

**Issue by pvamshi** [nnja/advanced-git#8]
I was trying out the slides . At slide no 15, 
```
echo 'blob 14\0Hello, World!' | openssl sha1
```
returns the following hash
```
5ad1cb82b3edb9d3ef1ae227745c90bcd23d2120
```
which is wrong. 

we need to escape the characters, so `-e` needs to be passed to `echo`
```
echo -e 'blob 14\0Hello, World!' | openssl sha1
```

this gives the correct output.

**Comment by nnja** [comment]
Thank you for bringing this up. Unfortunately the behavior of echo is different on different operating systems, so it works fine without -e on MacOS, but not on Linux and Windows.

**Comment by nnja** [comment]
If you'd like to add a brief note about it in the README for this repo and open a PR I'd be happy to merge it.
